FROM node:22-alpine

WORKDIR /app


# Copy package files
COPY package.json ./
COPY yarn.lock ./

# Install dependencies
RUN yarn install

# Copy source code
COPY . .

# Expose port
EXPOSE 8000

# Use nodemon for development with file watching
CMD ["yarn", "start:dev"] 