version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_persist:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  # app:
  #   container_name: gglk
  #   restart: always
  #   build: .
  #   ports:
  #     - ${PORT}:${PORT}
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

volumes:
  db_persist:
