name: Publish to NPM

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - '.github/workflows/error-type-publish.yaml'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn build:packages

      - name: Version patch and push
        run: |
          git config user.name "${{ secrets.ACTION_GIT_USER_NAME }}"
          git config user.email "${{ secrets.ACTION_GIT_USER_EMAIL }}"
          cd packages/error-types
          yarn version --new-version patch -m "chore(release): %s"

      - name: Setup NPM Authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" >> ~/.npmrc
          cat ~/.npmrc

      - name: Publish to NPM
        run: |
          cd packages/error-types
          yarn publish --non-interactive --access public
