name: Publish to NPM

on:
  push:
    branches:
      - main
    paths:
      - 'libs/error-types/**'
      - '.github/workflows/error-type-publish.yaml'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: yarn install

      - name: Build library
        run: yarn build:lib:error-types

      - name: Version patch and push
        run: |
          cd libs/error-types
          git config user.name "${{ secrets.ACTION_GIT_USER_NAME }}"
          git config user.email "${{ secrets.ACTION_GIT_USER_EMAIL }}"
          yarn version --patch -m "chore(release): %s"
          git push origin HEAD
          git push origin --tags

      - name: Prepare for publish
        run: |
          cp libs/error-types/package.json dist/libs/error-types/src/
          cp libs/error-types/Readme.md dist/libs/error-types/src/

      - name: Publish to NPM
        run: |
          cd dist/libs/error-types/src
          yarn publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
