name: Publish to NPM

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - '.github/workflows/error-type-publish.yaml'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn build:packages

      - name: Version patch and push
        run: |
          git config user.name "${{ secrets.ACTION_GIT_USER_NAME }}"
          git config user.email "${{ secrets.ACTION_GIT_USER_EMAIL }}"
          yarn version patch -m "chore(release): %s"

      - name: Publish to NPM
        run: yarn publish:packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
